### ISSUE TITLE
crash when open statistic whit no data input before

### ISSUE THREAD

**Issue by muhammadarif1** [Baltasarq/nadamillas#1]
here is bug recording
https://youtu.be/ww2uaIkKdKI
here is logcat
```FATAL EXCEPTION: Thread-24261
Process: com.devbaltasarq.nadamillas, PID: 10439
java.lang.NumberFormatException: Invalid int: "null"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parseInt(Integer.java:358)
	at java.lang.Integer.parseInt(Integer.java:334)
	at java.lang.Integer.valueOf(Integer.java:525)
	at com.devbaltasarq.nadamillas.ui.StatsActivity.getSelections(StatsActivity.java:328)
	at com.devbaltasarq.nadamillas.ui.StatsActivity.access$200(StatsActivity.java:33)
	at com.devbaltasarq.nadamillas.ui.StatsActivity$7.run(StatsActivity.java:348)``


step to reproduce
- download the app
- open the app
- than click statistic option and see if the app will crash if no data input before

**Comment by Baltasarq** [comment]
Thanks for the bug report. Will fix it tomorrow, first thing.

**Comment by Baltasarq** [comment]
This has been fixed.
